//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUDT1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Empleado
    {
        [Display(Name = "ID")]
        public string Id { get; set; } // Propiedad para el ID del empleado

        [Display(Name = "Nombre del empleado")]
        public string Nombre { get; set; } // Propiedad para el nombre del empleado

        [Display(Name = "Salario")]
        public decimal Salario { get; set; } // Propiedad para el salario del empleado
    }
}
